# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Workflow to update data from folder data-raw and checkin the results

on:
  push:
    paths: ["data-raw/**"]

name: Build_data

jobs:
  build_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R packages
        run: |
          R -e 'install.packages("usethis")'
          R -e 'install.packages("readxl")'

      - name: Build_data
        run: Rscript data-raw/package_data.R

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add data/\*.rda
          git commit -m "Update data from data-raw" || echo "No changes to commit"
          git pull --ff-only
          git push origin
